### ISSUE TITLE
My modules are not working

### ISSUE THREAD

**Issue by enesuncuoglu** [ReversecLabs/drozer#118]
Hi,
I have the similar problem here: https://github.com/mwrlabs/drozer/issues/116. After installation of my module, drozer is crashing and exiting for all commands without any error message. I tried with normal commands, but it is still disconnecting from drozer. After I delete repository, commands work normally. Your sample module working but after install my module, drozer dont respond any command. I updated last commit https://github.com/mwrlabs/drozer/commit/81185c426559d2da68db16050fb74399e4dec648 , and installed the python-pip,  but still modules are not working.
Thanks for help

![capture](https://f.cloud.github.com/assets/3904991/2418368/cc3d520a-ab40-11e3-9060-76028a0407a5.PNG)

My sample code is here:

from drozer.modules import Module
class Info(Module):
name = ""
description = "A module that returns information about the device and hardware features"
examples = "run ex.cert.info"
date = ""
author = ""
license = "GNU GPL"
path = ["ex","cert"]
def execute(self, arguments):
build = self.new("android.os.Build")
self.stdout.write("Getting device info...\n")
self.stdout.write("[_] BOARD : %s\n" % (build.BOARD))
self.stdout.write("[_] BOOTLOADER : %s\n" % (build.BOOTLOADER))
self.stdout.write("[_] BRAND : %s\n" % (build.BRAND))
self.stdout.write("[_] CPU_ABI : %s\n" % (build.CPU_ABI))
self.stdout.write("[_] CPU_ABI2 : %s\n" % (build.CPU_ABI2))
self.stdout.write("[_] DEVICE : %s\n" % (build.DEVICE))
self.stdout.write("[_] DISPLAY : %s\n" % (build.DISPLAY))
self.stdout.write("[_] FINGERPRINT : %s\n" % (build.FINGERPRINT))
self.stdout.write("[_] HARDWARE : %s\n" % (build.HARDWARE))
self.stdout.write("[_] MANUFACTURER : %s\n" % (build.MANUFACTURER))
self.stdout.write("[_] MODEL : %s\n" % (build.MODEL))
self.stdout.write("[_] TAGS : %s\n" % (build.TAGS))

**Comment by myyuk** [comment]
hello ,i have the same problem with "unknown module"。I want know how to resolve the problem, who can help me，Thank you!
