### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by mspreitz** [ReversecLabs/drozer#127]
When running Drozer from a Mac to connect to an Android emulator I get the following error:

```
  $ drozer console connect
  Selecting a3c1645bb991da42 (unknown sdk 4.0.4)

            ..                    ..:.
           ..o..                  .r..
            ..a..  . ....... .  ..nd
              ro..idsnemesisand..pr
              .otectorandroidsneme.
           .,sisandprotectorandroids+.
         ..nemesisandprotectorandroidsn:.
        .emesisandprotectorandroidsnemes..
      ..isandp,..,rotectorandro,..,idsnem.
      .isisandp..rotectorandroid..snemisis.
      ,andprotectorandroidsnemisisandprotec.
     .torandroidsnemesisandprotectorandroid.
     .snemisisandprotectorandroidsnemesisan:
     .dprotectorandroidsnemesisandprotector.

  drozer Console (v2.3.3)
  [Errno 1] Operation not permitted
```

The agent on the emulator shows the following messages:
![bildschirmfoto 2014-06-19 um 09 30 36](https://cloud.githubusercontent.com/assets/1796101/3324730/a5478ed8-f783-11e3-874f-cc7a03184e9a.png)

Do you have any idea why there is an "operation not permitted"?

**Comment by DanoPlurana** [comment]
Hi, unfortunately I ve got the same problem. Could you please give me some tips?

OS - OS X Yosemite

**Comment by donwalrus** [comment]
I fought with this for a while. The first time I launched drozer console connect, it worked fine, then never thereafter...after much trial and error, I deleted the local drozer history file and viola!

`rm -rf ~/.drozer_history`

**Comment by cibermike20** [comment]
Hi everyone, if it wasn’t by donwalrus I would’ve crack my mac trying to figure out how to solve this problem. I’ve lost hours today due to this ridiculous error. How is possible to mantain this kind of issue years later? Is there any way to remove it with the aim of avoiding more people wasting time on this?
