### ISSUE TITLE
unknown module

### ISSUE THREAD

**Issue by adra1n** [ReversecLabs/drozer#141]
hello,I can run drozer ,but when I use 'run' ,it always cant find the module
![222](https://cloud.githubusercontent.com/assets/7148275/5375533/3ed085d6-80a6-11e4-8b8c-2fd1867da8d0.png)

**Comment by deepocean23** [comment]
@adra1n : I am also facing the same problem. Can you help how you changed path of the Drozer. Currently, my Drozer is installed at this location of C:\Python27\lib and its repository files in C:\Python27\Scripts\
This was installed by default as while installed, it didn't asked me to install for any specific location or change path.
Please help

**Comment by deepocean23** [comment]
I can see src/drozer/modules/app/package.py this file exist in drozer installation directory.
Please help
