### ISSUE TITLE
Run 'pip install twisted' to fetch this dependency.

### ISSUE THREAD

**Issue by vaibhavc418** [ReversecLabs/drozer#409]
┌──(kali㉿kali)-[~]
└─$ pip -V                
pip 23.2.1 from /home/kali/.local/lib/python3.11/site-packages/pip (python 3.11)

┌──(kali㉿kali)-[~]
└─$ python -V                     
Python 3.11.4

┌──(kali㉿kali)-[~]
└─$ python -m twisted --version 
22.10.0
                                                                                                                                                                       
┌──(kali㉿kali)-[~]
└─$ drozer console connect     
/usr/share/offsec-awae-wheels/pyOpenSSL-19.1.0-py2.py3-none-any.whl/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
drozer Server requires Twisted to run.
Run 'pip install twisted' to fetch this dependency.

**Comment by cyberMilosz** [comment]
Hi there, sorry for the delayed response!

drozer has some very specific (and dated) software pre-requisites, namely Python 2.7 and Java 7. We hope to resolve these issues in a future version, but we can't comment on when exactly that will happen.

In the meantime, the easier way to run drozer is through our official Docker container: https://hub.docker.com/r/withsecurelabs/drozer
