### ISSUE TITLE
Drozer does not run on Android 6 Marshmallow

### ISSUE THREAD

**Issue by unixsingh** [ReversecLabs/drozer#414]
I'm encountering an error while running Drozer.
Steps I followed:
- docker pull withsecurelabs/drozer
- adb forward tcp:31415 tcp:31415
- docker run --net host -it withsecurelabs/drozer console connect --server localhost

(The same problem persists by using the git clone and try running it)

See the reference error image below. FYI, drozer agent is installed and running on the Genymotion emulator.

![image](https://github.com/WithSecureLabs/drozer/assets/126919241/34b134eb-ae47-4797-ba85-9e69710a4aea)

**Comment by Yogehi** [comment]
![image](https://github.com/WithSecureLabs/drozer/assets/10925671/2f44eaf9-b21c-41f4-9f9c-aea7530e3c41)

yup it looks like drozer doesn't work on android marshmallow. we are investigating

**Comment by cyberMilosz** [comment]
Looks like we introduced a regression to old Android in the recent release. This is hopefully fixed in the `develop` branch now - but please let us know if you run into further issues with Android 6!

**Comment by cyberMilosz** [comment]
The docker container should now be up to date - let us know how you get on!

**Comment by unixsingh** [comment]
That's working now. Thanks team!
