### ISSUE TITLE
drozer is not on `PATH` due to how Kali does `pip`

### ISSUE THREAD

**Issue by Darkcast** [ReversecLabs/drozer#420]
update kali documentation to add the following since drozer doesnt install on a default kali path
 
```
# yes nano, I am a heathen  :)
nano ~/.zshrc 

# drozer path
export PATH=$PATH:/home/kali/.local/bin

source ~/.zshrc
```

**Comment by Yogehi** [comment]
1) congrats on being issue number 420

2) `nano` is love UwU

3) we'll look into this. It's technically not a drozer issue. It's a `pip` and how Kali does `pip` issue. So we are gonna discuss how to address this

**Comment by cyberMilosz** [comment]
Adjusted the Kali/Debian instructions to run `pip` as `sudo` - that way `pip` has access to normal site-packages, which in turn is already in `PATH` by default.

This will become a non-issue once we have a deb in Kali's repository anyway (hopefully soon).
