### ISSUE TITLE
kali can not use docker-drozer

### ISSUE THREAD

**Issue by kylian-8** [ReversecLabs/drozer#429]
Caught Exception cannot resolve com.WithSecure.dz.Agent
'NoneType' object has no attribute 'do_exit'

anyone can help please?

**Comment by Yogehi** [comment]
Need you to provide a full output of commands 

Like how did you launch the docker image, if you did proper `adb` commands, the drozer command you used, etc

**Comment by kylian-8** [comment]
![屏幕截图 2024-04-19 100500](https://github.com/WithSecureLabs/drozer/assets/149947030/ec1d9e97-6f88-4a15-ab47-d4fee226e7a6)
i think commands are all right...

**Comment by Yogehi** [comment]
What phone model are you using, and where did you install Drozer from?

**Comment by kylian-8** [comment]
using nox_simulator and install drozer-docker in this Proj's  Description

**Comment by Yogehi** [comment]
My bad, I meant to ask where did you install the drozer-agent from?

And "nox_simulator"...never heard of it. Will need to look into it. But is "nox_simulator" a "Xiaomi device"? I ask because your screenshots shows that you're trying to connect to a Xiaomi device?

**Comment by kylian-8** [comment]
sry,my bad
i used drozer in win11 last week somy drozer-agent  is 2.4.4.
and nox_simulator is an android simulator on windows.it is not a real simulator.
its name is fake
