### ISSUE TITLE
local variable 'session' referenced before assignment

### ISSUE THREAD

**Issue by ChandTH** [ReversecLabs/drozer#436]
When running this command: `drozer console connect` I get the following error:

```
Selecting 5501e6b36210b11 (unknown Nexus 4 6.0)

local variable 'session' referenced before assignment
```

I am using Genymotion Emulator with Google Nexus 6.0 (Marshmallow) 

Tried, installing two dedicated devices already. No help!

Possible solutions?

**Comment by Yogehi** [comment]
Please verify what version of Drozer on your PC you are running, and what version of Drozer is installed on the Genymotion

**Comment by ak-phyo** [comment]
> When running this command: `drozer console connect` I get the following error:
> 
> ```
> Selecting 5501e6b36210b11 (unknown Nexus 4 6.0)
> 
> local variable 'session' referenced before assignment
> ```
> 
> I am using Genymotion Emulator with Google Nexus 6.0 (Marshmallow)
> 
> Tried, installing two dedicated devices already. No help!
> 
> Possible solutions?

Hello, it is ok for me. You can see in screenshot. Make sure to check the version. 

![image](https://github.com/WithSecureLabs/drozer/assets/17943627/6ee951be-e108-41f4-a19e-81e1ba411982)

**Comment by Yogehi** [comment]
Closing due to lack of response front ticket opener
