### ISSUE TITLE
When using Docker to build an environment on a Mac, there seems to be network isolation, which prevents direct access.

### ISSUE THREAD

**Issue by three-person-007** [ReversecLabs/drozer#446]
I have forwarded the port of the Android emulator to the physical host 172.16.0.249, but I cannot see the corresponding device.
<img width="436" alt="image" src="https://github.com/WithSecureLabs/drozer/assets/64969459/63cd4c8d-3afb-4553-a2d4-2c0fa92cf15b">
<img width="912" alt="image" src="https://github.com/WithSecureLabs/drozer/assets/64969459/b54ac19b-ba2e-4cd5-947f-4adacd1f92d4">

**Comment by cyberMilosz** [comment]
That sounds like a networking issue on your end, not a drozer issue.

You _could_ try using `adb forward` as described [here](https://github.com/WithSecureLabs/drozer?tab=readme-ov-file#option-2-connect-to-the-phone-via-usb)

**Comment by three-person-007** [comment]
Thank you very much for your reply. I have solved the problem. It was due to the network communication issue between Docker and the host machine. I found the solution in the "issues" section.[https://github.com/WithSecureLabs/drozer/issues/325](url)
