### ISSUE TITLE
'local variable 'session' referenced before assignment' error

### ISSUE THREAD

**Issue by cosm0snnt** [ReversecLabs/drozer#453]
Drozer show these messages.

```
D:\Python2.7.16(64-bit)>cd D:\Python2.7.16(64-bit)

D:\Python2.7.16(64-bit)>adb forward tcp:31415 tcp:31415

D:\Python2.7.16(64-bit)>drozer console connect
Selecting 9f985db032125619 (samsung SM-G965N 9)

local variable 'session' referenced before assignment


D:\Python2.7.16(64-bit)>
```

How can I edit drozer code or something else that I can fix this problem? I'm on Windows 11(Surface Pro 6). Thanks.

**Comment by WilliamBenEmbarek** [comment]
Please read the readme file. Drozer uses Python3. Python2.7 has been end of life for 13 years now.

**Comment by cyberMilosz** [comment]
Hey! It sounds like you might be using Python 2. If that's the case, please have a look at the [README](https://github.com/WithSecureLabs/drozer?tab=readme-ov-file#software-pre-requisites). We only support Python 3.8 and above.
