### ISSUE TITLE
Broken release tag url on README.md

### ISSUE THREAD

**Issue by ajutamangdev** [ReversecLabs/drozer#463]
Its redirecting to the broken URL https://github.com/WithSecureLabs/drozer/releases/tag/latest.

Hyperlink should be updated with this url instead https://github.com/WithSecureLabs/drozer/releases

![release](https://github.com/user-attachments/assets/02212a3a-9474-4c29-8c5a-5fd2ba42d30f)

**Comment by cyberMilosz** [comment]
Thanks for pointing this out! Tweaked.
