### ISSUE TITLE
Drozer console connect - Help plz

### ISSUE THREAD

**Issue by Ryu9999** [ReversecLabs/drozer#471]
I want to use the drozer automation tool that runs in python. 
On Windows laptops, vm and nox both use the 192.x.x.x band. 
However, it is impossible to use adb connect [destination IP]:62001 as shown below. 
AI says Nox adb is designed for local connections, so do additional forwarding or connect locally. 
I want to connect the nox package installed on one window using vm and adb.

Note: I tried to use this tool.  https://github.com/themalwarenews/drozscan

C:\Users\FE!N\Desktop\platform-tools-latest-windows\platform-tools>tasklist |findstr "Nox"
Nox.exe                      36764 Console                    1     36,048 K
NoxVMSVC.exe                 19808 Console                    1     22,552 K
NoxVMHandle.exe              47780 Console                    1    137,080 K

C:\Users\FE!N\Desktop\platform-tools-latest-windows\platform-tools>netstat -ano | findstr 47780
  TCP    127.0.0.1:56001        0.0.0.0:0              LISTENING       47780
  TCP    127.0.0.1:57001        0.0.0.0:0              LISTENING       47780
  TCP    127.0.0.1:58001        0.0.0.0:0              LISTENING       47780
  TCP    127.0.0.1:58001        127.0.0.1:56114        ESTABLISHED     47780
  TCP    127.0.0.1:60001        0.0.0.0:0              LISTENING       47780
  TCP    127.0.0.1:61001        0.0.0.0:0              LISTENING       47780
  TCP    127.0.0.1:61001        127.0.0.1:56166        ESTABLISHED     47780
  TCP    127.0.0.1:62002        0.0.0.0:0              LISTENING       47780
  TCP    127.0.0.1:62002        127.0.0.1:56192        ESTABLISHED     47780
  TCP    127.0.0.1:63001        0.0.0.0:0              LISTENING       47780
  TCP    127.0.0.1:64001        0.0.0.0:0              LISTENING       47780
  UDP    127.0.0.1:52001        *:*                                    47780
  UDP    127.0.0.1:59001        *:*                                    47780
  UDP    127.0.0.1:65001        *:*                                    47780

**Comment by cyberMilosz** [comment]
I'm sorry, but this is not a drozer problem. I had a quick look, and both adb and drozer seem to work just fine with NoxPlayer.

![image](https://github.com/user-attachments/assets/4b7cd9ae-d025-4890-ae0c-e05fabee4b81)

The only slight annoyance I've observed is that NoxPlayer insists on running its own adb server, which doesn't match the version of the adb client on my machine. Looks like you could use `nox_adb.exe` inside of Nox's folders to make that work.

![image](https://github.com/user-attachments/assets/22c39dbf-b7ba-48a7-b5c1-2470932fc634)

Looking at this "drozscan" tool, it should pretty much just work from this point.

Please don't talk to "AI" chatbots for computing advice. Learn your environment.
