### ISSUE TITLE
Import Error for drozer.cli

### ISSUE THREAD

**Issue by wolfkabal** [ReversecLabs/drozer#87]
Drozer 2.3.0

Error Message:
D:\drozer>drozer.bat console connect
Traceback (most recent call last):
  File "D:\drozer\bin\drozer", line 24, in <module> **import**("drozer.cli.%s" % (sys.argv[1]))
ImportError: No module named drozer.cli.console

Environment: Windows 7 x64 using the setup.exe for installation. ADB and Java installed and included in PATH.

It gives the ImportError: No module named drozer.cli.X for all valid commands.

**Comment by wqching** [comment]
same problem with you.
