### ISSUE TITLE
.drozer_config java path problem under winnt

### ISSUE THREAD

**Issue by hellok** [ReversecLabs/drozer#92]
maybe this is how to modify .drozer_config

[executables]
java = C:\Program Files\Java\jre7\bin\java.exe

**Comment by wangfuwen000** [comment]
sorry， it does't work after create drozer_config file, then reinstall drozer, still does't work


 error message;

Could not find java. Please ensure that it is installed and on your PATH.

If this error persists, specify the path in the ~/.drozer_config file:

    [executables]
    java = C:\path\to\java
There was a problem connecting to the drozer Server.

Things to check:

 - is the drozer Server running?
 - have you set up appropriate adb port forwards?
 - have you specified the correct hostname and port with --server?
 - is the server protected with SSL (add an --ssl switch)?
 - is the agent protected with a password (add a --password switch)?

Debug Information:
[Errno 10061]

so  the question how to find 10061 bug???

**Comment by wangfuwen000** [comment]
i get it , the answer is:

[executables]

java =C:\Program Files\Java\jdk1.7.0_40\bin\java.exe

javac =C:\Program Files\Java\jdk1.7.0_04\bin\javac.exe

dx =F:\Android\android-sdk_r18-windows\android-sdk-windows\platform-tools\dx.bat

 

3、put the file in you pc：

englihs：C:\Users\<youruser name>\

chinese：C:\用户\<你的用户名名称>\

4、rename file with cmd commands：.drozer_config

rename  C:\Users\d00218136\1.txt .drozer_config

**Comment by myhappyday99** [comment]
i create a file in C:\Users\my username\my username.drozer_config and it contains the text:
[executables]
java = C:\Program Files (x86)\Java\jdk1.7.0_45\bin\java.exe
but could not find java~~~~
did i write wrong directory or wrong text?

**Comment by myhappyday99** [comment]
![1](https://cloud.githubusercontent.com/assets/11328010/6501151/c39ce0b0-c2c9-11e4-9410-a745309d8e43.png)

**Comment by dadpour** [comment]
@dbradberry thanks 
But to fix it,
create ".drozer_config" file that contain the text:
```
[executables]
java = C:\Program Files\Java\jdk1.7.0_40\bin\java.exe
```
<h6> save it in "drozer" directory. </h6>

**Comment by APOORVMAGAN** [comment]
@dadpour 
Nothing happens by creating .drozer_config with that text in it

**Comment by truedelguyin** [comment]
does anyone got the solution for using drozer on windows, its giving me the same error message, path not found

**Comment by APOORVMAGAN** [comment]
Make .drozer_config file in user and set both java and javax path and save
that .drozer_ config in users

Regards:
APOORV MAGAN
9789712135

**Comment by APOORVMAGAN** [comment]
Sorry , Java and javac path.

Regards:
APOORV MAGAN
9789712135

**Comment by truedelguyin** [comment]
I have saved the path to .drozer_config
[executables]
java = C:\Program Files\Java\jre6\bin
javac= C:\Program Files\Java\jre6\bin\javac.exe

but its still not working. does we need to mention and specific extension for .drozer_config?

**Comment by truedelguyin** [comment]
does drozer only works with jdk 1.6?

**Comment by HenryHoggard** [comment]
> "does drozer only works with jdk 1.6?"

The current version of Drozer only works with JDK 1.6. The develop branch of Drozer now works with JDK 1.7 and 1.8.
